**Problem Statement**

This project analyzes Amazon e-commerce sales data to identify key revenue drivers, operational inefficiencies, and actionable insights across product categories, fulfillment methods, and geographic regions.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
#

In [2]:
ECom = pd.read_csv('/content/Amazon Sale Report.csv', engine = 'python' , on_bad_lines = 'skip')

In [3]:
ECom.head(5)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [4]:
ECom.shape

(128975, 24)

In [5]:
ECom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [6]:
ECom.describe()

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

In [7]:
ECom.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [8]:
Missing_Amount = ECom[ECom['Amount'].isnull()]

In [9]:
Missing_Amount.groupby(['ASIN' , 'Courier Status' , 'B2B']).size()

ASIN        Courier Status  B2B
B01LYC0N7Q  Cancelled       False    1
B01LZYQ93J  Cancelled       False    1
B01M3P3VPV  Cancelled       False    3
B01MSEK1O5  Cancelled       False    1
B01MZGYNRV  Cancelled       False    1
                                    ..
B0B3N6LVQD  Cancelled       False    1
B0B3NB42VV  Cancelled       False    1
B0B3NBR6SP  Cancelled       False    1
B0B3NBYD9W  Cancelled       False    1
B0B3NGN95V  Cancelled       False    1
Length: 2528, dtype: int64

In [10]:
print(Missing_Amount['Courier Status'].value_counts())
print(Missing_Amount['B2B'].value_counts())

Courier Status
Cancelled    5935
Unshipped     124
Name: count, dtype: int64
B2B
False    7767
True       28
Name: count, dtype: int64

In [11]:
ECom_sales = ECom[ECom['Courier Status'] != 'Cancelled']

In [12]:
print(f'Rows removed: {len(ECom) - len(ECom_sales)}')
print(f'Missing Amount after: {ECom_sales["Amount"].isnull().sum()}')

Rows removed: 5935
Missing Amount after: 1860

In [13]:
Missing_Amount_After = ECom_sales[ECom_sales['Amount'].isnull()]
print(Missing_Amount_After['Courier Status'].value_counts())
print(Missing_Amount_After['B2B'].value_counts())

Courier Status
Unshipped    124
Name: count, dtype: int64
B2B
False    1855
True        5
Name: count, dtype: int64

In [14]:
print(f'Total_missing: {ECom_sales['Amount'].isnull().sum()}')
print(f'Missing_rate: {(1860/len(ECom_sales)* 100):.2f}%')

Total_missing: 1860
Missing_rate: 1.51%

In [15]:
ECom_clean = ECom_sales[~ ECom_sales['Courier Status'].isin(['Cancelled' , 'Unshipped'])]

print(f'Missing Amount After: {ECom_clean['Amount'].isnull().sum()}')
print(f'Missing rate: {(ECom_clean['Amount'].isnull().sum() / len(ECom_clean) * 100):.2f}%')

Missing Amount After: 1736
Missing rate: 1.49%

In [16]:
ECom.shape

(128975, 24)

In [17]:
ECom_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 116359 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               116359 non-null  int64
 1   Order ID            116359 non-null  object
 2   Date                116359 non-null  object
 3   Status              116359 non-null  object
 4   Fulfilment          116359 non-null  object
 5   Sales Channel       116359 non-null  object
 6   ship-service-level  116359 non-null  object
 7   Style               116359 non-null  object
 8   SKU                 116359 non-null  object
 9   Category            116359 non-null  object
 10  Size                116359 non-null  object
 11  ASIN                116359 non-null  object
 12  Courier Status      109487 non-null  object
 13  Qty                 116359 non-null  int64
 14  currency            114623 non-null  object
 15  Amount              114623 non-null  float64
 16  ship-city           116330 non-null  object
 17  ship-state          116330 non-null  object
 18  ship-postal-code    116330 non-null  float64
 19  ship-country        116330 non-null  object
 20  promotion-ids       78681 non-null   object
 21  B2B                 116359 non-null  bool
 22  fulfilled-by        38753 non-null   object
 23  Unnamed: 22         71711 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 21.4+ MB

In [18]:
print('=== DATA CLEANING DECISION LOG ===\n')


print('Column: promotion-ids')
print(f'Non-null: {ECom_clean['promotion-ids'].isnull().sum()}/{len(ECom_clean)} (68.5%)')
print(' Decision: Drop - Not essential for core sales analysis')
print(' Reason: For this project , analyzing overall sales trend > promo effectiveness\n')

print('Column: fulfilled-by')
print(f'Non-null: {ECom_clean['fulfilled-by'].isnull().sum()}/{len(ECom_clean)} (33.3%)')
print(' Decision: Drop - Too sparse (66.7% missing) & not core to analysis')
print(' Reason: Focus on revenue & customer behavior , not fulfillment channels\n')

ECom_final = ECom_clean.drop(columns=['promotion-ids' , 'fulfilled-by'])
print(f'Final dataset: {ECom_final.shape}')

=== DATA CLEANING DECISION LOG ===

Column: promotion-ids
Non-null: 37678/116359 (68.5%)
 Decision: Drop - Not essential for core sales analysis
 Reason: For this project , analyzing overall sales trend > promo effectiveness

Column: fulfilled-by
Non-null: 77606/116359 (33.3%)
 Decision: Drop - Too sparse (66.7% missing) & not core to analysis
 Reason: Focus on revenue & customer behavior , not fulfillment channels

Final dataset: (116359, 22)

In [19]:
ECom_final.describe()

               index            Qty         Amount  ship-postal-code
count  116359.000000  116359.000000  114623.000000     116330.000000
mean    64094.749628       0.944456     647.765599     463078.647082
std     37266.296537       0.246985     281.599510     191517.739979
min         0.000000       0.000000       0.000000     110001.000000
25%     31813.500000       1.000000     449.000000     382110.000000
50%     63887.000000       1.000000     604.760000     500032.000000
75%     96682.500000       1.000000     788.000000     600019.000000
max    128974.000000       8.000000    5584.000000     989898.000000

In [20]:
ECom_final.dtypes

index                   int64
Order ID               object
Date                   object
Status                 object
Fulfilment             object
Sales Channel          object
ship-service-level     object
Style                  object
SKU                    object
Category               object
Size                   object
ASIN                   object
Courier Status         object
Qty                     int64
currency               object
Amount                float64
ship-city              object
ship-state             object
ship-postal-code      float64
ship-country           object
B2B                      bool
Unnamed: 22            object
dtype: object

In [21]:
ECom_final.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               1736
Amount                 1736
ship-city                29
ship-state               29
ship-postal-code         29
ship-country             29
B2B                       0
Unnamed: 22           44648
dtype: int64

In [22]:
ECom_final.describe()

               index            Qty         Amount  ship-postal-code
count  116359.000000  116359.000000  114623.000000     116330.000000
mean    64094.749628       0.944456     647.765599     463078.647082
std     37266.296537       0.246985     281.599510     191517.739979
min         0.000000       0.000000       0.000000     110001.000000
25%     31813.500000       1.000000     449.000000     382110.000000
50%     63887.000000       1.000000     604.760000     500032.000000
75%     96682.500000       1.000000     788.000000     600019.000000
max    128974.000000       8.000000    5584.000000     989898.000000

In [23]:
# Standardize all column names
ECom_final.columns = ECom_final.columns.str.strip()  # Remove spaces
ECom_final.columns = ECom_final.columns.str.lower()  # Make lowercase
ECom_final.columns = ECom_final.columns.str.replace(' ', '_')  # Replace spaces with underscores

# Now all your columns will be clean and consistent
print(ECom_final.columns)

Index(['index', 'order_id', 'date', 'status', 'fulfilment', 'sales_channel',
       'ship-service-level', 'style', 'sku', 'category', 'size', 'asin',
       'courier_status', 'qty', 'currency', 'amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'b2b', 'unnamed:_22'],
      dtype='object')

In [24]:
ECom_final.drop('unnamed:_22' , axis = 1 , inplace = True)

In [25]:
print("Missing Values in Courier_Status:")
print(ECom_final['courier_status'].value_counts(dropna=False))

Missing Values in Courier_Status:
courier_status
Shipped    109487
NaN          6872
Name: count, dtype: int64

In [26]:
ECom_final['courier_status'] = ECom_final['courier_status'].fillna(ECom_final.apply(lambda row: 'Cancelled' if row['status'] == 'Cancelled' else ECom_final['courier_status'].mode()[0], axis = 1))
print(f"Missing Value after fill: {ECom_final['courier_status'].isnull().sum()}")

Missing Value after fill: 0

In [27]:
ECom_final['currency'].fillna('INR' , inplace = True)

In [28]:
# Check how many missing amounts
print("Missing values in Amount column:")
print(f"Total missing: {ECom_final['amount'].isnull().sum()}")
print(f"Percentage: {(ECom_final['amount'].isnull().sum() / len(ECom_final) * 100):.2f}%")

# Check if they correlate with any status
missing_amount_data = ECom_final[ECom_final['amount'].isnull()]
print("\nMissing amounts by Status:")
print(missing_amount_data['status'].value_counts())

Missing values in Amount column:
Total missing: 1736
Percentage: 1.49%

Missing amounts by Status:
status
Cancelled                       1725
Shipped - Delivered to Buyer       8
Shipped - Returned to Seller       3
Name: count, dtype: int64

In [29]:
print("=== AMOUNT CLEANUP ===")
before = len(ECom_final)
ECom_final = ECom_final.dropna(subset=['amount'])
after = len(ECom_final)

print(f"✅ Rows removed: {before - after}")
print(f"✅ Final dataset: {after} rows")
print(f"✅ Missing amounts: {ECom_final['amount'].isnull().sum()}")

# Final quality check
print(f"\n=== FINAL DATA QUALITY ===")
print(f"Missing values:\n{ECom_final.isnull().sum()}")
print(f"\nData Quality Score: {(1 - ECom_final.isnull().sum().sum() / (len(ECom_final) * len(ECom_final.columns))) * 100:.2f}%")

=== AMOUNT CLEANUP ===
✅ Rows removed: 1736
✅ Final dataset: 114623 rows
✅ Missing amounts: 0

=== FINAL DATA QUALITY ===
Missing values:
index                  0
order_id               0
date                   0
status                 0
fulfilment             0
sales_channel          0
ship-service-level     0
style                  0
sku                    0
category               0
size                   0
asin                   0
courier_status         0
qty                    0
currency               0
amount                 0
ship-city             29
ship-state            29
ship-postal-code      29
ship-country          29
b2b                    0
dtype: int64

Data Quality Score: 100.00%

In [30]:
## Revenue Metrics
Total_Revenue = ECom_final['amount'].sum()
print('Total_Revenue:' , Total_Revenue)
Avg_Order_Value = ECom_final['amount'].mean()
print('Avg_Order_Value:' , Avg_Order_Value)

Total_Revenue: 74248836.30000001
Avg_Order_Value: 647.7655993997715

In [31]:
## Top Categories
Top_Categories = ECom_final.groupby('category')['amount'].sum().sort_values(ascending =False).head(10)
print('Top 10 Categories:' , Top_Categories)

Top 10 Categories: category
Set              36981843.03
kurta            20124081.70
Western Dress    10669066.69
Top               5010092.30
Ethnic Dress       757546.66
Blouse             439879.18
Bottom             145292.98
Saree              120118.76
Dupatta               915.00
Name: amount, dtype: float64

In [32]:
## B2B vs B2C
B2B_B2C = ECom_final.groupby('b2b')['amount'].agg(['sum', 'mean', 'count'])
print('B2B_Analysis:', B2B_B2C)

B2B_Analysis:                sum        mean   count
b2b
False  73681429.51  647.395964  113812
True     567406.79  699.638459     811

In [33]:
## Top Products

Top_Products = ECom_final.groupby('sku')['amount'].sum().sort_values(ascending = False).head(10)
print('Top 10 Products:' , Top_Products)

Top 10 Products: sku
JNE3797-KR-L       501626.77
J0230-SKD-M        490784.20
J0230-SKD-S        450016.14
JNE3797-KR-M       434309.16
JNE3797-KR-S       394439.57
JNE3797-KR-XL      312066.24
JNE3797-KR-XS      284266.70
J0230-SKD-L        282869.95
JNE3797-KR-XXL     267793.88
JNE3797-KR-XXXL    262939.80
Name: amount, dtype: float64

In [34]:
## Order Status Impact
Status_Analysis = ECom_final.groupby('status')['amount'].agg(['sum' , 'mean' , 'count'])
print('Status Analysis:', Status_Analysis )

Status Analysis:                                       sum         mean  count
status
Cancelled                       3190172.3   621.139467   5136
Pending                            7679.0   767.900000     10
Shipped                        50324255.0   648.541871  77596
Shipped - Damaged                  1136.0  1136.000000      1
Shipped - Delivered to Buyer   18650815.0   648.475887  28761
Shipped - Lost in Transit          1997.0   399.400000      5
Shipped - Out for Delivery        26971.0   770.600000     35
Shipped - Picked Up              661252.0   679.601233    973
Shipped - Rejected by Buyer        7295.0   663.181818     11
Shipped - Returned to Seller    1269644.0   651.099487   1950
Shipped - Returning to Seller    107620.0   742.206897    145

In [35]:
# Export cleaned data for Power BI
ECom_final.to_csv('ECom_final_cleaned.csv', index=False)
print("Data exported successfully!")
print(f"File size: {ECom_final.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

Data exported successfully!
File size: 104.47 MB

In [36]:
print("=" * 60)
print("KEY INSIGHTS FROM ANALYSIS")
print("=" * 60)

print("\n1. TOP REVENUE DRIVER:")
print(f"   Category: {Top_Categories.index[0]}")
print(f"   Revenue: ${Top_Categories.values[0]:,.0f}")

print("\n2. B2B vs B2C:")
b2b_sum = B2B_B2C.loc[True, 'sum']
b2c_sum = B2B_B2C.loc[False, 'sum']
print(f"   B2C: ${b2c_sum:,.0f} ({b2c_sum/(b2b_sum+b2c_sum)*100:.1f}%)")
print(f"   B2B: ${b2b_sum:,.0f} ({b2b_sum/(b2b_sum+b2c_sum)*100:.1f}%)")

print("\n3. TOP PRODUCT:")
print(f"   SKU: {Top_Products.index[0]}")
print(f"   Revenue: ${Top_Products.values[0]:,.0f}")

print("\n4. ORDER STATUS:")
print(f"   Shipped %: {(Status_Analysis.loc['Shipped', 'sum'] / Status_Analysis['sum'].sum() * 100):.1f}%")

============================================================
KEY INSIGHTS FROM ANALYSIS
============================================================

1. TOP REVENUE DRIVER:
   Category: Set
   Revenue: $36,981,843

2. B2B vs B2C:
   B2C: $73,681,430 (99.2%)
   B2B: $567,407 (0.8%)

3. TOP PRODUCT:
   SKU: JNE3797-KR-L
   Revenue: $501,627

4. ORDER STATUS:
   Shipped %: 67.8%

In [37]:
ECom_final.shape

(114623, 21)

In [38]:
# Before any processing
print(f"Original shape: {ECom.shape}")
print(f"Original rows: {len(ECom)}")

# At the end
print(f"Final shape: {ECom_final.shape}")
print(f"Rows removed: {115000 - len(ECom_final)}")

Original shape: (128975, 24)
Original rows: 128975
Final shape: (114623, 21)
Rows removed: 377